/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_jnitest_JNIutils */

#ifndef _Included_com_example_administrator_jnitest_JNIutils
#define _Included_com_example_administrator_jnitest_JNIutils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_jnitest_JNIutils
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_jnitest_JNIutils_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
